#!/usr/bin/env node
/**
 * Generate Handoff Script
 * Tạo developer handoff document
 */

const fs = require('fs');
const path = require('path');

const OUTPUT_DIR = path.resolve(__dirname, '../../../../output/design');
const MASTER_FILE = path.join(OUTPUT_DIR, 'MASTER.md');
const HANDOFF_FILE = path.join(OUTPUT_DIR, 'handoff.md');
const PAGES_DIR = path.join(OUTPUT_DIR, 'pages');

// Extract colors from MASTER.md
const extractColors = (content) => {
    const colors = {};
    const colorMatches = content.matchAll(/\|\s*([\w\s]+)\s*\|\s*(#[A-Fa-f0-9]{6})\s*\|/g);
    for (const match of colorMatches) {
        const name = match[1].trim().toLowerCase().replace(/\s+/g, '-');
        colors[name] = match[2];
    }
    return colors;
};

// Generate handoff
const generateHandoff = () => {
    console.log('\n========================================');
    console.log('   DEVELOPER HANDOFF GENERATOR');
    console.log('========================================\n');

    if (!fs.existsSync(MASTER_FILE)) {
        console.log('[!] No MASTER.md found. Run generate-design.js first.');
        return;
    }

    const masterContent = fs.readFileSync(MASTER_FILE, 'utf8');
    const colors = extractColors(masterContent);

    // Get page specs
    const pages = [];
    if (fs.existsSync(PAGES_DIR)) {
        const pageFiles = fs.readdirSync(PAGES_DIR).filter(f => f.endsWith('.md'));
        pages.push(...pageFiles.map(f => f.replace('.md', '')));
    }

    const timestamp = new Date().toISOString();

    const handoff = `# Developer Handoff

## Design System Files

| File | Description |
|------|-------------|
| \`output/design/MASTER.md\` | Global design tokens |
${pages.map(p => `| \`output/design/pages/${p}.md\` | ${p.charAt(0).toUpperCase() + p.slice(1)} page spec |`).join('\n')}

---

## Quick Start

### 1. CSS Variables

\`\`\`css
:root {
${Object.entries(colors).slice(0, 15).map(([name, hex]) => `  --${name}: ${hex};`).join('\n')}
}
\`\`\`

### 2. Tailwind Config

\`\`\`js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
${Object.entries(colors).slice(0, 10).map(([name, hex]) => `        '${name}': '${hex}',`).join('\n')}
      },
    },
  },
};
\`\`\`

### 3. Font Setup

\`\`\`html
<!-- Add to <head> -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
\`\`\`

\`\`\`css
body {
  font-family: 'Inter', system-ui, sans-serif;
}
\`\`\`

---

## Component Library

### Recommended: shadcn/ui

\`\`\`bash
# Initialize shadcn/ui
npx shadcn-ui@latest init

# Add components
npx shadcn-ui@latest add button
npx shadcn-ui@latest add card
npx shadcn-ui@latest add input
\`\`\`

### Icon Set: Lucide Icons

\`\`\`bash
npm install lucide-react
\`\`\`

\`\`\`jsx
import { Home, Settings, User } from 'lucide-react';
\`\`\`

---

## Implementation Checklist

### Setup
- [ ] Install Tailwind CSS
- [ ] Configure CSS variables
- [ ] Add font (Inter)
- [ ] Set up component library

### Pages
${pages.map(p => `- [ ] Implement ${p} page`).join('\n') || '- [ ] No pages defined yet'}

### Quality
- [ ] Test responsive breakpoints
- [ ] Verify color contrast (accessibility)
- [ ] Add loading states
- [ ] Add error states

---

## Responsive Guidelines

| Breakpoint | Width | Layout |
|------------|-------|--------|
| Mobile | < 640px | Single column, stacked |
| Tablet | 640-1024px | Two columns, collapsible sidebar |
| Desktop | > 1024px | Full layout, fixed sidebar |

---

## Animation Guidelines

### Transitions
- Use \`150ms ease\` for micro-interactions (hover, focus)
- Use \`200ms ease\` for state changes (open/close)
- Use \`300ms ease\` for page transitions

### Hover States
- Buttons: darken by 10%
- Cards: slight shadow increase
- Links: underline or color change

---

## Accessibility Notes

1. **Color Contrast**: Ensure 4.5:1 ratio for text
2. **Focus States**: Visible focus ring on interactive elements
3. **Touch Targets**: Minimum 44x44px
4. **Alt Text**: All images need descriptive alt text
5. **Keyboard Navigation**: All actions accessible via keyboard

---

## Resources

- [MASTER.md](./MASTER.md) - Full design tokens
- [Tailwind CSS Docs](https://tailwindcss.com/docs)
- [shadcn/ui](https://ui.shadcn.com/)
- [Lucide Icons](https://lucide.dev/)

---

*Generated by UI-UX Skill | ${timestamp}*
`;

    fs.writeFileSync(HANDOFF_FILE, handoff, 'utf8');
    console.log(`[OK] Handoff saved to: ${HANDOFF_FILE}`);
    console.log(`\nIncludes:`);
    console.log(`  - ${Object.keys(colors).length} color tokens`);
    console.log(`  - ${pages.length} page references`);
    console.log(`  - Quick start guides`);
};

generateHandoff();
