#!/usr/bin/env node
/**
 * Start Intake Script
 * Khởi tạo và quản lý intake session
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const OUTPUT_DIR = path.resolve(__dirname, '../../../../output/intake');
const INTAKE_FILE = path.join(OUTPUT_DIR, 'intake.md');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Intake template
const createIntakeTemplate = (data) => {
    const timestamp = new Date().toISOString();
    return `# Intake: ${data.projectName || 'Untitled Project'}

## Project Overview
- **Type**: ${data.projectType || 'TBD'}
- **Scale**: ${data.scale || 'TBD'}
- **Tech Stack**: ${data.techStack || 'TBD'}

## Target Users

### Primary User
- **Who**: ${data.primaryUser?.who || 'TBD'}
- **Pain Points**: ${data.primaryUser?.painPoints || 'TBD'}
- **Goals**: ${data.primaryUser?.goals || 'TBD'}

### Secondary Users
${data.secondaryUsers?.length ? data.secondaryUsers.map(u => `- ${u}`).join('\n') : '- None specified'}

## Features

### Must-Have (P0)
${data.mustHaveFeatures?.length ? data.mustHaveFeatures.map((f, i) => `${i + 1}. ${f}`).join('\n') : '- TBD'}

### Nice-to-Have (P1)
${data.niceToHaveFeatures?.length ? data.niceToHaveFeatures.map((f, i) => `${i + 1}. ${f}`).join('\n') : '- None specified'}

### Out of Scope
${data.outOfScope?.length ? data.outOfScope.map(s => `- ${s}`).join('\n') : '- Not defined yet'}

## Constraints
- **Timeline**: ${data.timeline || 'TBD'}
- **Budget**: ${data.budget || 'N/A'}
- **Tech Stack Requirements**: ${data.techRequirements || 'None'}
- **Performance Requirements**: ${data.performanceReqs || 'Standard'}

## Existing Context
- **Codebase**: ${data.existingCodebase || 'No'}
- **Design Files**: ${data.designFiles || 'No'}
- **Documentation**: ${data.existingDocs || 'No'}

## Integrations
${data.integrations?.length ? data.integrations.map(i => `- ${i}`).join('\n') : '- None specified'}

## Deployment
- **Environment**: ${data.deployEnv || 'TBD'}
- **Platform**: ${data.deployPlatform || 'TBD'}

## Open Questions
${data.openQuestions?.length ? data.openQuestions.map((q, i) => `${i + 1}. ${q}`).join('\n') : '- No open questions'}

## Next Steps
- [ ] Address open questions
- [ ] Proceed to Research phase
- [ ] Proceed to Spec phase

---
*Generated by Intake Skill | Date: ${timestamp}*
`;
};

// Interactive mode
const startInteractiveIntake = async () => {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    const ask = (question) => new Promise((resolve) => {
        rl.question(question, (answer) => resolve(answer.trim()));
    });

    console.log('\n========================================');
    console.log('   INTAKE SESSION - Thu thập yêu cầu');
    console.log('========================================\n');
    console.log('Gõ "skip" để bỏ qua câu hỏi');
    console.log('Gõ "quit" để thoát và lưu\n');

    const data = {
        mustHaveFeatures: [],
        niceToHaveFeatures: [],
        outOfScope: [],
        secondaryUsers: [],
        integrations: [],
        openQuestions: []
    };

    try {
        // Project basics
        data.projectName = await ask('1. Tên dự án: ');
        if (data.projectName === 'quit') throw new Error('User quit');

        data.projectType = await ask('2. Loại dự án (Web App/Mobile/API/CLI/Library/Desktop): ');
        data.scale = await ask('3. Quy mô (MVP/Product/Enterprise): ');
        data.techStack = await ask('4. Tech stack mong muốn (hoặc skip): ');

        // Users
        console.log('\n--- TARGET USERS ---');
        const primaryWho = await ask('5. Người dùng chính là ai? ');
        const primaryPain = await ask('6. Họ gặp vấn đề gì? ');
        const primaryGoal = await ask('7. Họ muốn đạt được gì? ');

        data.primaryUser = {
            who: primaryWho !== 'skip' ? primaryWho : 'TBD',
            painPoints: primaryPain !== 'skip' ? primaryPain : 'TBD',
            goals: primaryGoal !== 'skip' ? primaryGoal : 'TBD'
        };

        // Features
        console.log('\n--- FEATURES ---');
        console.log('Nhập từng feature, gõ "done" khi xong');

        console.log('\nMust-have features (P0):');
        let input = '';
        while ((input = await ask('  - ')) !== 'done' && input !== 'quit') {
            if (input && input !== 'skip') data.mustHaveFeatures.push(input);
        }

        console.log('\nNice-to-have features (P1):');
        while ((input = await ask('  - ')) !== 'done' && input !== 'quit') {
            if (input && input !== 'skip') data.niceToHaveFeatures.push(input);
        }

        // Constraints
        console.log('\n--- CONSTRAINTS ---');
        data.timeline = await ask('8. Timeline/Deadline: ');
        data.budget = await ask('9. Budget (hoặc skip): ');
        data.techRequirements = await ask('10. Tech requirements bắt buộc: ');

        // Existing context
        console.log('\n--- EXISTING CONTEXT ---');
        data.existingCodebase = await ask('11. Có code sẵn không? (Yes/No + chi tiết): ');
        data.designFiles = await ask('12. Có design files không? (Yes/No + chi tiết): ');

        // Deployment
        console.log('\n--- DEPLOYMENT ---');
        data.deployPlatform = await ask('13. Deploy ở đâu? (AWS/GCP/Vercel/etc): ');

        // Open questions
        console.log('\n--- OPEN QUESTIONS ---');
        console.log('Còn câu hỏi nào cần clarify? (gõ "done" khi xong)');
        while ((input = await ask('  ? ')) !== 'done' && input !== 'quit') {
            if (input && input !== 'skip') data.openQuestions.push(input);
        }

    } catch (e) {
        console.log('\n[!] Session ended early');
    }

    rl.close();

    // Generate and save
    const content = createIntakeTemplate(data);
    fs.writeFileSync(INTAKE_FILE, content, 'utf8');
    console.log(`\n[OK] Intake saved to: ${INTAKE_FILE}`);
    console.log('\nNext steps:');
    console.log('  1. Review intake.md');
    console.log('  2. Run research skill to find similar repos');
    console.log('  3. Run spec-kit to create specifications');
};

// Quick mode - from arguments or stdin
const quickIntake = (args) => {
    const data = {
        projectName: args.name || 'Quick Project',
        projectType: args.type || 'TBD',
        scale: args.scale || 'MVP',
        techStack: args.tech || 'TBD',
        mustHaveFeatures: args.features ? args.features.split(',') : [],
        niceToHaveFeatures: [],
        outOfScope: [],
        secondaryUsers: [],
        integrations: [],
        openQuestions: ['Cần clarify thêm chi tiết']
    };

    const content = createIntakeTemplate(data);
    fs.writeFileSync(INTAKE_FILE, content, 'utf8');
    console.log(`[OK] Quick intake saved to: ${INTAKE_FILE}`);
};

// Parse args
const args = process.argv.slice(2);
const options = {};
for (let i = 0; i < args.length; i += 2) {
    if (args[i].startsWith('--')) {
        options[args[i].slice(2)] = args[i + 1];
    }
}

if (options.quick) {
    quickIntake(options);
} else {
    startInteractiveIntake();
}
